# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '4.3'
target 'YouQiu' do
  # Comment the next line if you don't want to use dynamic frameworks
  source 'https://github.com/artsy/Specs.git' 
  source 'https://github.com/CocoaPods/Specs.git'
    pod 'SVProgressHUD'  # 弹窗
    pod 'Masonry' #自动布局框架
  end

  # Pods for YouQiu

  target 'YouQiuTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YouQiuUITests' do
    # Pods for testing
  end

